# This is a basic workflow to help you get started with Actions

on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
      uses: appleboy/jenkins-action@master
      with:
        url: "http://3.12.111.34:8080/"
        user: "admin1"
        token: ${{ secrets.TOKEN1 }}
        job: "ex_job"
