
on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: "Trigger jenkins job"
      uses: GoldenspearLLC/build-jenkins-job@master
      with:
        jenkins-url: ${{ secrets.JENKINS_URL }}
        jenkins-token: ${{ secrets.TOKEN1 }}
        user: "admin1"
        job-path: "job/folder_name/job/job_name"
        job-params: "{'param1': 'value1', 'param2': 'value2'}"
    - name: Get job status
      run: echo "Job status is ${{ steps.job-build.outputs.job_status }}"
